<!DOCTYPE HTML>
<!--
	Boiled Frog - Climate Change Awareness and Strategy
	Ian D James
-->
<html>
	<head>
 		<title>Boiled Frog- Climate Change Government Policy</title>
		<meta name="description" content="Climate Change Criminality">
		<meta name="author" content="Ian James">
		<meta charset="utf-8" />
		<meta name="keywords" content="environment, climate, change, global, warming, greenhouse, enhanced, effect, accountability, criminality, cuplability, IPCC, NASA">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="assets/css/main.css" />

		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-58191121-2"></script>
		<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-58191121-2');
		</script>


	</head>

	<body class="subpage">

		<!-- Header -->
		<?php include 'header.html';?>

		<!-- Nav -->
		<?php include 'navigation.html';?>

		<!-- One -->
			<section id="One" class="wrapper style3">
				<div class="inner">
					<header class="align-center">
						<p>Government Policy</p>
						<h2>Environment and Climate Policies</h2>
					</header>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper style2">
				<div class="inner">
					<div class="box">
						<div class="content">
							<header class="align-center">
								<p>William E. Gladstone</p>
								<h3>When there’s a vacuum of public input, lobbyists usually fill it. But when<br />
									there’s public input, the people usually win.
								</h3>
							</header>
							<br /><br />
							<p>As individuals, most of us understand what we can do to reduce emissions: save energy, use the car less, recycle more, 
							make better consumption choices, and engage in family planning. But what can our governments do? </p>
							<h3>Limiting Emissions - Carbon Tax</h3>
							<img style="float:left; solid gray; height:263px; width:341px; margin-bottom:8px; margin-right:24px;" src="./images/carbon tax2.jpg" />
							<p>Carbon tax is a form of pollution tax. It levies a fee on the production, distribution or use of fossil fuels based on how much 
							carbon their combustion emits. The government sets a price per ton on carbon, then translates it into a tax on electricity, natural 
							gas or oil. Because the tax makes using dirty fuels more­ expensive, it encourages utilities, businesses and individuals to reduce 
							consumption and increase energy efficiency. Carbon tax also makes alternative energy more cost-competitive with cheaper, 
							polluting fuels like coal, natural gas and oil.</p>

							<p>Carbon tax is based on the economic principle of negative externalities. Externalities are costs or benefits generated by the 
							production of goods and services. Negative externalities are costs that are not paid for. When utilities, businesses or homeowners
							 consume fossil fuels, they create pollution that has a societal cost; everyone suffers from the effects of pollution. Proponents 
							 of a carbon tax believe that the price of fossil fuels should account for these societal costs. More simply put -- if you're 
							 polluting to everyone else's detriment, you should have to pay for it.</p>
							<p>There are two main types of carbon pricing: emissions trading systems (ETS) and carbon taxes.</p>
							<p style="margin-left:30px;"><b>ETS</b>: sometimes referred to as a cap-and-trade system, it caps the total level of greenhouse gas emissions and lowers the cap over 
							time. Companies are allowed a limited, and falling, number of emissions permits. Those industries with low emissions are able to sell 
							their extra allowances to larger emitters. By creating supply and demand for emissions allowances, an ETS establishes a market price 
							for greenhouse gas emissions. The cap helps ensure that the required emission reductions will take place to keep the emitters (in aggregate) 
							within their pre-allocated carbon budget.</p>

							<p style="margin-left:30px;"><b>Carbon tax</b>: directly sets a price on carbon by defining a tax rate on greenhouse gas emissions or – more commonly – on the carbon content 
							of fossil fuels. It is different from an ETS in that the emission reduction outcome of a carbon tax is not pre-defined but the carbon price is.</p>

							<iframe style="float:right; margin-right:20px;" width="600" height="315" src="https://www.youtube.com/embed/xHIGuk27jVY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

							<p style="margin-top:15px;">Implementation of carbon pricing may be resisted if selectively adopted by the international market. In an open global economy, 
							adopting companies and countries risk being put in a pricing and competitive disadvantage. The World Bank's <a target="_blank" href="https://carbonpricingdashboard.worldbank.org/map_data">carbon 
							pricing dashboard</a> provides a summary of regional, national and subnational carbon pricing initiatives, both implemented or scheduled for implementation.</p> 
							<p>The <a target="_blank" href="https://www.cdp.net/en/climate/carbon-pricing/carbon-pricing-connect">Carbon Pricing Leadership Coalition</a> provides a global disclosure system that enables companies, cities, states and regions to measure and manage their environmental 
							impacts. They have built a comprehensive collection of self-reported environmental data.</p>
							<br />
							<h3>Protect and Restore Ecosystems</h3>
							<p>Governments must preserve and restore ecosystems, particularly rivers, wetlands, oceans, riparian forests and mangroves. Policies may include:</p>
							<img style="float:left; solid gray; height:450px; width:361px; margin-bottom:8px; margin-right:24px;" src="./images/habitat-restoration.jpg" />
							<p>
								<ul style="width: auto; overflow: hidden;">
									<li>Establishing protected areas through legal measures can serve to protect and preserve critical ecosystems</li>
									<li>Land purchases and establishment of conservation easements. Public and private purchases of ecologically valuable 
										land as well as establishment of conservation easements, i.e., the purchase of development rights</li>
									<li><a target="_blank" href="https://www.iucn.org/commissions/commission-ecosystem-management/our-work/cems-thematic-groups/ecosystem-restoration">Restore</a> or assist the recovery of habitats and ecosystems that have been degraded, damaged or destroyed</li>
								</ul>
							</p>

							<h3>Transition to Small Agricultural Producers</h3>

							<p>According to the Food and Agriculture Organization of the United Nations, the meat industry is responsible for 15 - 18 percent of all greenhouse 
							   gas emissions, exceeding even those of the transportation sector. In addition, it is the most significant source of water use and contamination in 
							   the world. Today, 80 percent of all agricultural production goes toward feeding animals not people. The expansion of land for livestock, and the 
							   crops to feed them, is the most significant cause of deforestation in the Amazon.</p>
							<p>Governments should increasingly support small regional producers who, unlike the large factory farms, employ more sustainable practices including 
							   land management and restoration.</p>

							<h3>Promote Renewable (Green) Energy</h3>
							<img style="float:right; solid gray; height:608px; width:367px; margin-bottom:8px; margin-left:24px;" src="./images/green-energy.jpg" />
							
							<p>According to the Global Energy Network Institute, the following government policies prove most effective for promoting renewable energy:</p>
							<ul style="width: auto; overflow: hidden;">
									<li><b>Performance standards</b>: For example, fuel efficiency standards for vehicles and buildings, including lighting, windows, 
									ventilation, heating and cooling systems.</li>
									<li><b>Fiscal instruments</b>: Some countries offer tax exemptions or tax breaks for appliances and energy efficiency improvements.</li>
									<li><b>Targets and timetables</b>: For example, setting renewable portfolio standards (RPS), mandating that a percentage of all energy  
									purchases be derived from renewable resources</li>
									<li><b>Technology performance standards</b>: For example, vehicle pollution standards and energy star</li>
									<li><b>Taxes and fees</b>: For example, higher taxes on fossil-fuel energy sources thereby increasing renewable energy competiveness</li>
									<li><b>Tariffs</b>: For example, private energy producer "feed-in" tariffs, establishing predictable market pricing for smaller energy producers</li>
									<li><b>Subsidy reform</b>: For example, reducing subsidies for the fossil-fuel industries</li>
									<li><b>Trade policies</b>: For eaxmple, cutting tariffs on green goods such as solar panels, wind turbines, and energy-efficient light bulbs can help ensure access to the best technologies available globally.</li>
									<li><b>Venture capital provision</b>: For example, renewable enery equity funding for renewable energy start-up companies</li>
									<li><b>Technology procurement</b>: For example, government guarantees for market demand</li>

								</ul>

							<h3>Reduce Short-Lived Climate Pollutants</h3>

							<p>Unlike CO2, which may require millennia for reabsorption, there are many contaminants that contribute to climate change that only last a few days 
							   or years in the atmosphere. They’re known as short-lived climate pollutants, and they’re responsible for 30 to 45 percent of the emissions that 
							   cause global warming. These pollutants include black carbon (soot), methane, ozone, and the hydro fluorocarbons found in refrigerants. Their 
							   effective control, through national policies and regulations, could accelerate the fight against climate change in the short term.</p>

							
							<img style="float:left; border:1px solid gray; height:263px; width:300px; margin-bottom:8px; margin-right:24px;" src="./images/un-logo.png" />
							<h3>International Agreements</h3>

							<p>The <a target="_blank" href="https://www.consilium.europa.eu/en/policies/climate-change/international-agreements-climate-action/">United Nations 
							Framework Convention on Climate Change (UNFCCC)</a> is the main international agreement on climate action. It was one of three conventions adopted 
							at the Rio Earth Summit in 1992. To date, it has been ratified by 195 countries. It started as a way for countries to work together to limit global 
							temperature increases and climate change, and to cope with their impacts.</p>

							<h3>Kyoto Protocol</h3>

							<p>In the mid 1990s, the UNFCCC signatories realised that stronger provisions were needed to reduce emissions. In 1997, they agreed the Kyoto 
							   Protocol, which introduced legally binding emission reduction targets for developed countries.</p>
							
							<p>The second commitment period of the Kyoto Protocol began on 1 January 2013 and will end in 2020. 38 developed countries, including the EU and 
							   its 28 member states, are participating. This second period is covered by the Doha amendment, under which participating countries have committed 
							   to reducing emissions by at least 18% below 1990 levels. The EU has committed to reducing emissions in this period to 20% below 1990 levels.</p>

							<p>The main weakness of the Kyoto Protocol is that it only requires developed countries to take action. As the United States has never signed up to 
							   the Kyoto Protocol, Canada pulled out before the end of the first commitment period and Russia, Japan and New Zealand are not taking part in the 
							   second commitment period, it also only now applies to around 14% of the world's emissions. However, more than 70 developing and developed countries 
							   have made various non-binding commitments to reduce or limit their greenhouse gas emissions.</p>

							<h3>Paris Agreement</h3>

							<p>At the Paris climate conference (COP21) in December 2015, 195 countries adopted the first-ever universal, legally binding global climate deal.
							   The agreement sets out a global action plan to put the world on track to avoid dangerous climate change by limiting global warming to well 
							    below 2°C and pursuing efforts to limit it to 1.5°C. Governments agreed:</p>
							<ul style="margin-left:30px;">
								<li>to a long-term goal of keeping the increase in global average temperature to well below 2°C above pre-industrial levels</li>
								<li>to aim to limit the increase to 1.5°C, since this would significantly reduce risks and the impacts of climate change</li>
								<li>on the need for global emissions to peak as soon as possible, recognising that this will take longer for developing countries</li>
								<li>to undertake rapid reductions thereafter in accordance with the best available science</li>
								<li>to come together every 5 years to set more ambitious targets as required by science</li>
								<li>to report to each other and the public on how well they are doing to implement their targets</li>
								<li>to track progress towards the long-term goal through a robust transparency and accountability system</li>
								<li>to strengthen societies' ability to deal with the impacts of climate change</li>
								<li>to provide continued and enhanced international support for adaptation to developing countries</li>
							</ul>

							<p>On June 1, 2017, United States President Donald Trump announced that the U.S. would cease all participation in the 2015 Paris 
							   Agreement on climate change mitigation. Trump stated that "The Paris accord will undermine the U.S. economy," and "puts the U.S. at a permanent disadvantage. 
							   In accordance with Article 28 of the Paris Agreement, the earliest possible effective withdrawal date by the United States cannot be before November 4, 2020.</p>

							<h3>United States - The Green Deal</h3>
							<img style="float:left; border:1px solid gray; height:342px; width:263px; margin-bottom:8px; margin-right:24px;" src="./images/green-deal.png" />
							
							
							<p>Introduced by Sen. Ed Markey (D-MA) and Rep. Alexandrai Ocasio-Cortez (D-NY), the <b>Green New Deal</b> is not just another climate policy. It recognizes the requirement to mobilize and address climate change and its many interconnected economic, social, political and ecological issues. It argues that we no longer have the luxury of time to 
							implement incremental or surgical climate policy changes - that opportunity has come and gone. Instead, the crisis demands our collective resolve to adopt timely and comprehensive policy change. Mass mobilization is required to avoid imminent ecological and economic disaster.  
							
							<p>Unfortunately, the policy may prove too broad as it seeks to address both climate change and economic inequality. Its socialist theme will likely alienate many who would otherwise support climate change policies. Nonetheless, the green deal 
							serves as an important wake-up call, recognizing the peril of status quo. It proposes a much broader scope and scale of policy change to address our ever accelerating ecological crisis.</p>

							<br /><br />

							<p><i>"We cannot deal with the climate crisis, much less the overall planetary ecological emergency, in an effective way while conforming to the logic of a globalized capitalist economy. But we currently live in such an economy, and we have a very short time 
							in which to respond to climate change. So, it becomes a question of immediately choosing to steer society toward putting people and nature before profits, as opposed to what capitalism does, i.e. putting profits before people and nature. We have to go against 
							the logic of the system even while living within it."</i><br /><br /> <b> John Bellamy Foster</b> - professor of sociology at the University of Oregon</p>
							<p>Full details of the new green deal can be read <a target="_blank" href="./assets/content/Green-New-Deal-final.pdf">here</a>.</p>
						</div>
					</div>
				</div>
			</section>

		<!-- Footer -->
		<footer id="footer">
				<div class="logo"><a target="_blank" href="https://boiledfrog.ca"><img src="images/logo.png" /></a></div>
				<div class="copy">Boiled Frog &copy;2019 All rights reserved<div class="security"><a target="_blank" href="https://www.rapidssl.com"><img src="images/RapidSSL.png" /></a></div></div>
				<div class="container">
					
					<ul style="margin-bottom:10px;" class="icons">
						<li><a href="https://boiledfrog.ca" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="https://boiledfrog.ca" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="https://boiledfrog.ca" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="mailto:admin@boiledfrog.ca?Subject=Boiled Frog" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
					</ul>

				</div>
				
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>